// Generates src/stdlib-bundle.ts, embedding every std/*.milo file as a string.
//
// The formatter's source goes in too: a shipped binary has no repo to build fmt.milo
// from, and `milo fmt` / LSP format-on-save both need it (see src/fmtbin.ts).
import { readdirSync, readFileSync, writeFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const stdDir = resolve(root, "std");
const outFile = resolve(root, "src", "stdlib-bundle.ts");

const files = readdirSync(stdDir).filter(f => f.endsWith(".milo")).sort();
const entries = files.map(f => {
  const content = readFileSync(resolve(stdDir, f), "utf-8");
  return `  [${JSON.stringify("std/" + f)}, ${JSON.stringify(content)}]`;
});

// Kept out of STDLIB so it can't show up in stdlib enumeration (`milo api`,
// goto-definition) — it's a shipped tool's source, not part of the std surface.
const fmtSource = readFileSync(resolve(root, "examples", "cli-tools", "fmt.milo"), "utf-8");

const code = `// auto-generated by scripts/bundle-stdlib.ts — do not edit
export const STDLIB: Map<string, string> = new Map([
${entries.join(",\n")}
]);

export const FMT_SOURCE: string = ${JSON.stringify(fmtSource)};
`;

writeFileSync(outFile, code);
console.log(`bundled ${files.length} stdlib files + fmt.milo → src/stdlib-bundle.ts`);
