// Renders the Homebrew formula for a release and prints it to stdout.
//
//   bun scripts/render-formula.ts <version> <artifacts-dir> [commit] > milo.rb
//
// <artifacts-dir> holds the milo-<target>.tar.gz files, which are hashed here rather
// than passed in — a formula whose sha256 doesn't match what the release actually
// serves is the classic tap breakage, and reading the bytes makes it impossible.
//
// The output goes in milo-language/homebrew-tap as Formula/milo.rb, so users get
// `brew install milo-language/tap/milo`. A tap needs no review; homebrew-core (bare
// `brew install milo`) has a notability bar Milo hasn't cleared yet.

import { createHash } from "crypto";
import { readFileSync } from "fs";
import { join } from "path";
import { TARGETS, tarballUrl } from "./release-meta";

const [version, artifacts, commitArg] = process.argv.slice(2);
if (!version || !artifacts) {
  console.error("usage: render-formula.ts <version> <artifacts-dir> [commit]");
  process.exit(1);
}
// Homebrew's `version` has to stay clean semver for its comparison rules, so the
// commit rides along as a comment rather than in the version string. It is still the
// thing you need when a tap user reports a bug against "0.1.0".
const commit = (commitArg ?? process.env.GITHUB_SHA ?? "").slice(0, 7);

const sha = (target: string) =>
  createHash("sha256")
    .update(readFileSync(join(artifacts, `milo-${target}.tar.gz`)))
    .digest("hex");

// The tarball unpacks to a milo-<target>/ directory, so the install path is not a bare
// `bin.install "milo"` — it has to reach inside.
const arm = (os: string) => TARGETS.find(t => t.os === os && t.cpu === "arm64")!.target;
const intel = (os: string) => TARGETS.find(t => t.os === os && t.cpu === "x64")!.target;

const block = (target: string, indent: string) =>
  [
    `${indent}url "${tarballUrl(version, target)}"`,
    `${indent}sha256 "${sha(target)}"`,
  ].join("\n");

process.stdout.write(`# Generated by scripts/render-formula.ts — do not edit by hand.
${commit ? `# milo ${version}, built from commit ${commit}.\n` : ""}class Milo < Formula
  desc "Memory-safe systems language that compiles to LLVM IR"
  homepage "https://milo-language.github.io/milo/"
  version "${version}"
  license "MIT"

  on_macos do
    on_arm do
${block(arm("darwin"), "      ")}
    end
    on_intel do
${block(intel("darwin"), "      ")}
    end
  end

  on_linux do
    on_arm do
${block(arm("linux"), "      ")}
    end
    on_intel do
${block(intel("linux"), "      ")}
    end
  end

  # No depends_on "llvm": milo only needs a *linker driver*, and pulling in the llvm
  # keg would make a ~2 GB download the default install for a 60 MB compiler. macOS
  # already ships clang with the Command Line Tools.
  def caveats
    <<~EOS
      milo links what it compiles with clang.
        macOS: install the Xcode Command Line Tools — xcode-select --install
        Linux: install your distribution's clang, or run: brew install llvm
    EOS
  end

  def install
    # Homebrew strips a single root directory when it stages a tarball, so the binary
    # normally lands at the top level; the nested path is the fallback if that changes.
    src = File.exist?("milo") ? "milo" : Dir["milo-*/milo"].first
    bin.install src => "milo"
  end

  test do
    assert_match "milo ${version}", shell_output("#{bin}/milo --version")
    (testpath/"hello.milo").write <<~MILO
      pub fn main(): i32 {
          print("hello")
          return 0
      }
    MILO
    # emit-ir, not run: the brew test sandbox has no guarantee of a working linker,
    # and everything up to the link is what this is checking.
    assert_match "define i32 @main", shell_output("#{bin}/milo emit-ir hello.milo")
  end
end
`);
