#!/bin/sh
# Build milo-self (the Milo compiler written in Milo) with the TS compiler.
# The TS compiler is the oracle; this script only produces the stage-1 binary.
# Exits nonzero if it does not build. See docs/self-hosting.md.
#
# The build runs under scripts/guard.ts so a runaway build can never eat all
# system memory (macOS enforces no rlimits — the guard is the only real cap).
#
# The REAL binary is .selfhost/milo-self.bin. .selfhost/milo-self is a
# self-guarding wrapper: any bare invocation — human or agent — gets the RSS
# watchdog automatically, so forgetting the guard can no longer crash the OS.
# Test harnesses call milo-self.bin directly via guardedRun (single guard).
set -e

root=$(cd "$(dirname "$0")/.." && pwd)
out="$root/.selfhost"
mkdir -p "$out"

# --mem-mb is explicit, not left to the guard's default. The default is
# min(4096, RAM/4), so the SAME command enforced a different cap per machine: 4096 MB on a
# 16 GB dev Mac, 1792 MB on a 7 GB CI runner — where it SIGKILLed this build, produced no
# milo-self.bin, and surfaced as the fixpoint failing at stage 2 with "No such file or
# directory". A build's memory need is a property of the build, not of whoever runs it.
#
# 3072 is at or below the previous effective cap on every machine that was passing, so this
# tightens more hosts than it loosens, and it stays under the guard's own half-of-RAM
# backstop on anything with 8 GB or more. Below that the backstop fires first, which is the
# correct direction to fail.
bun "$root/scripts/guard.ts" --mem-mb 3072 --virtual-mem-mb 8192 --timeout-s 300 -- \
  bun run "$root/src/main.ts" build "$root/src-milo/main.milo" -o "$out/milo-self.bin" "$@"

cat > "$out/milo-self" <<EOF
#!/bin/sh
# Auto-generated by scripts/selfhost.sh. milo-self has known memory bugs;
# this wrapper forces every invocation through the RSS/timeout guard.
# Never run milo-self.bin bare.
exec bun "$root/scripts/guard.ts" -- "$out/milo-self.bin" "\$@"
EOF
chmod +x "$out/milo-self"
